name: Build Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Make Gradle wrapper executable
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # 5. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 6. Run Gradle build task
      - name: Build the project with Gradle
        run: ./gradlew build

      # 7. Run tests with Gradle
      - name: Run tests with Gradle
        run: ./gradlew test

      # 8. Archive build artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-build-artifacts
          path: app/build/outputs/
