name: Codacy Analysis and Coverage

on:
  pull_request:
    branches:
      - main
      - releases/**
  push:
    branches:
      - main
      - releases/**

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - name: Prettier Format Check
        run: npm run format-check
      - name: ESLint Check
        run: npm run lint
      - name: Build & Test
        run: npm run test

  # Codacy Analysis
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.4.0
        with:
          verbose: true
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          format: json
          output: codacy-analysis-results.json
          directory: ./ # Directory to analyze
          upload: true
          max-allowed-issues: 100
          tool-timeout: 15minutes

      - name: Upload Codacy Coverage Report
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: "coverage/lcov-report/index.html"
          language: "javascript"
          force-coverage-parser: "lcov"

  # Git Version Calculation
  git-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main
          dev-branch: dev
          prefix: v
          log-paths: ./src # Change this to your source folder or use default
