# This workflow will build an Android project using Gradle and Java 17.
# It will run on every push to the main branch and pull requests.

name: Build Android Project

# Trigger this workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Define the environment
    runs-on: ubuntu-latest
    
    # Define the steps to run
    steps:
    
    # 1. Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 2. Set up Java 17 (required for Android projects)
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    # 3. Cache Gradle dependencies to improve workflow performance
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 4. Install Gradle (if not already available)
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # 5. Run Gradle build task to build the Android project
    - name: Build the project with Gradle
      run: ./gradlew build

    # 6. Run tests after build
    - name: Run tests with Gradle
      run: ./gradlew test

    # 7. Archive build artifacts
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build-artifacts
        path: app/build/outputs/
