name: Analyze with Soot

on:
  push:
    branches: 
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # تحميل مستودع الكود
      - name: Checkout Code
        uses: actions/checkout@v4

      # إعداد Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # تحميل Soot من GitHub
      - name: Download Soot
        run: |
          wget https://github.com/soot-oss/soot/releases/download/v4.2.1/soot-4.2.1.jar -P /home/runner/soot/

      # تحليل الكود باستخدام Soot
      - name: Analyze with Soot
        run: |
          java -jar /home/runner/soot/soot-4.2.1.jar -cp ./build/classes -output-dir ./soot-output --cfg
